### ISSUE TITLE
@nuxt/icon vs nuxt-icon

### ISSUE THREAD

**Issue by caio-emidio** [MonkeyDevelopers/template-#5]
@nuxt/icon nao funciona junto com a lib

Verificar pq

**Comment by caio-emidio** [comment]
![image](https://github.com/user-attachments/assets/b6266337-6825-4946-bdbe-9ba0ead6b902)

**Comment by caio-emidio** [comment]
Siga os passos
https://nuxt.com/modules/icon

**Comment by daviprm** [comment]
this issue has been resolved.

cause of the bug: in the new lib, there is a property called render mode, and by default it is in 'css', that is, a span is created with classes... the bug occurred because we also used span,. so just setting the render-mode to SVG in nuxt.config.ts file solved the problem.

![image](https://github.com/user-attachments/assets/6b2c6807-1a14-47ec-9e73-e571e996eb52)
![image](https://github.com/user-attachments/assets/a1d16797-a5f9-40b8-af86-a5db6d2e54fa)

https://nuxt.com/modules/icon#usage
